"""
Build a tidy multi-year OEWS national panel from the zips placed under
data/raw/large/oews/oesm{YY}nat.zip by `fetch_oews_year.py`.

Schema reconciled across 2012–2023 (national totals only):
- 2012–2018 files have one national row per occupation in `OCC_CODE`.
- 2019+ files include AREA / NAICS / OWN_CODE; we filter to AREA == 99 (U.S.),
  cross-industry, and prefer ownership 1235 (all ownerships) when present.

Output:
- data/processed/oews_national_panel_long.csv  — one row per (year, soc_code)
- data/meta/OEWS_PANEL_SNAPSHOT.md              — coverage + caveats

SOC vintage: OEWS uses **SOC 2010** through May 2019 and **SOC 2018** from
May 2020 onward. We DO NOT crosswalk in this script; we attach a
`soc_vintage` column so downstream merges (e.g. with AIOE which is SOC 2010)
can apply a crosswalk explicitly.
"""
from __future__ import annotations

import io
import sys
import zipfile
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = ROOT / "data" / "raw" / "large" / "oews"
PROCESSED = ROOT / "data" / "processed"
META = ROOT / "data" / "meta"

OUT_CSV = PROCESSED / "oews_national_panel_long.csv"
OUT_MD = META / "OEWS_PANEL_SNAPSHOT.md"

# Columns we want (subset present in *every* year 2012–2023).
KEEP_COMMON = [
    "OCC_CODE",
    "OCC_TITLE",
    "TOT_EMP",
    "A_MEAN",
    "A_MEDIAN",
    "A_PCT10",
    "A_PCT90",
]


def _coerce_numeric(s: pd.Series) -> pd.Series:
    return pd.to_numeric(s, errors="coerce")


def _read_year(zip_path: Path) -> pd.DataFrame:
    year = int("20" + zip_path.stem.replace("oesm", "").replace("nat", ""))
    with zipfile.ZipFile(zip_path) as z:
        name = next(
            (n for n in z.namelist() if "national" in n.lower() and n.lower().endswith((".xlsx", ".xls"))),
            None,
        )
        if name is None:
            raise FileNotFoundError(f"No national_*.xls(x) inside {zip_path}")
        with z.open(name) as f:
            df = pd.read_excel(io.BytesIO(f.read()))

    cols = set(df.columns)
    if "AREA" in cols:
        df = df[df["AREA"] == 99]
    if "I_GROUP" in cols:
        df = df[df["I_GROUP"].astype(str).str.lower() == "cross-industry"]
    if "OWN_CODE" in cols:
        own_pref = sorted(df["OWN_CODE"].dropna().unique().tolist(), key=lambda v: 0 if v == 1235 else 1)
        if own_pref:
            df = df[df["OWN_CODE"] == own_pref[0]]

    missing = [c for c in KEEP_COMMON if c not in df.columns]
    if missing:
        raise KeyError(f"{zip_path.name} missing expected columns: {missing}")

    out = df[KEEP_COMMON].copy()
    for c in ["TOT_EMP", "A_MEAN", "A_MEDIAN", "A_PCT10", "A_PCT90"]:
        out[c] = _coerce_numeric(out[c])

    out.rename(
        columns={
            "OCC_CODE": "soc_code",
            "OCC_TITLE": "soc_title",
            "TOT_EMP": "tot_emp",
            "A_MEAN": "annual_mean_wage",
            "A_MEDIAN": "annual_median_wage",
            "A_PCT10": "annual_p10_wage",
            "A_PCT90": "annual_p90_wage",
        },
        inplace=True,
    )
    out["year"] = year
    out["soc_vintage"] = "SOC2010" if year <= 2019 else "SOC2018"
    out["source_file"] = zip_path.relative_to(ROOT).as_posix()
    return out


def main() -> None:
    if not RAW_DIR.is_dir():
        print(f"No OEWS dir at {RAW_DIR}. Run fetch_oews_year.py first.", file=sys.stderr)
        sys.exit(1)

    zips = sorted(RAW_DIR.glob("oesm*nat.zip"))
    if not zips:
        print(f"No oesm*nat.zip in {RAW_DIR}. Run fetch_oews_year.py first.", file=sys.stderr)
        sys.exit(1)

    frames: list[pd.DataFrame] = []
    for z in zips:
        try:
            frames.append(_read_year(z))
            print(f"[ok] {z.name}: {len(frames[-1])} rows")
        except Exception as e:
            print(f"[skip] {z.name}: {e}", file=sys.stderr)

    if not frames:
        print("No OEWS frames ingested.", file=sys.stderr)
        sys.exit(2)

    panel = pd.concat(frames, ignore_index=True)
    panel = panel.sort_values(["year", "soc_code"]).reset_index(drop=True)

    PROCESSED.mkdir(parents=True, exist_ok=True)
    META.mkdir(parents=True, exist_ok=True)
    panel.to_csv(OUT_CSV, index=False)

    # Snapshot
    years = sorted(panel["year"].unique())
    n_per_year = panel.groupby("year").size().to_dict()
    n_unique_soc_per_year = panel.groupby("year")["soc_code"].nunique().to_dict()
    suppressed_emp = panel.groupby("year")["tot_emp"].apply(lambda s: int(s.isna().sum())).to_dict()

    lines = [
        "# OEWS national panel — snapshot",
        "",
        "Generated by `scripts/narrative/ingest_oews_panel.py`.",
        "",
        "| Aspect | Detail |",
        "|--------|--------|",
        "| Provider | **U.S. Bureau of Labor Statistics — OEWS** |",
        "| Geography | National (AREA=99), cross-industry |",
        "| Reference period | May of each survey year |",
        "| Years on disk | " + ", ".join(str(y) for y in years) + " |",
        f"| Total rows | {len(panel):,} |",
        "| Source files | `data/raw/large/oews/oesm{YY}nat.zip` |",
        "",
        "## Coverage by year",
        "",
        "| year | rows | unique SOC | rows w/ suppressed `tot_emp` | SOC vintage |",
        "|---:|---:|---:|---:|:--|",
    ]
    for y in years:
        vint = "SOC2010" if y <= 2019 else "SOC2018"
        lines.append(
            f"| {y} | {n_per_year.get(y, 0):,} | {n_unique_soc_per_year.get(y, 0):,} | "
            f"{suppressed_emp.get(y, 0):,} | {vint} |"
        )

    lines.extend(
        [
            "",
            "## Caveats",
            "",
            "- OEWS uses **SOC 2010** through May 2019 and **SOC 2018** from May 2020 onward — see `soc_vintage` column.",
            "- Wage and employment values can be **suppressed** (rendered as `*` / `**` upstream); they appear as `NaN` here.",
            "- A subset of newer files include `OWN_CODE`; we prefer ownership `1235` (all ownerships) where present.",
            "- For matching to AIOE (SOC 2010), apply the BLS SOC 2010 → 2018 crosswalk before joining post-2019 rows.",
            "",
            "## Processed file",
            "",
            f"- `{OUT_CSV.relative_to(ROOT).as_posix()}` — long format, one row per (year × SOC).",
            "",
        ]
    )
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {OUT_CSV} ({len(panel):,} rows)")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
