"""
Parse the newest data/raw/bls/ces_sample_*.json into:
  - data/processed/bls_ces_national_monthly_long.csv
  - data/meta/DATA_SNAPSHOT.md (sources + basic stats)

Run after fetch_bls_series.py.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
RAW_BLS = ROOT / "data" / "raw" / "bls"
PROCESSED = ROOT / "data" / "processed"
META = ROOT / "data" / "meta"

SERIES_LABELS = {
    "CES0000000001": "total_nonfarm",
    "CES6500000001": "education_and_health",
    "CES6000000001": "professional_and_business_services",
    "CES3100000001": "manufacturing",
}

SOURCE_LINES = """| Aspect | Detail |
|--------|--------|
| Provider | **U.S. Bureau of Labor Statistics (BLS)** |
| Program | Current Employment Statistics (CES) |
| Geography | National (U.S.) |
| Frequency | Monthly |
| Observation | All employees, **thousands**, **seasonally adjusted** |
| Retrieval | `POST https://api.bls.gov/publicAPI/v2/timeseries/data/` |
| Retrieval date | {retrieval_date} |
| Raw JSON | `data/raw/bls/` (timestamped `ces_sample_*.json`) |

**Series IDs (official CES)**

| Series ID | Label used in CSV |
|-----------|-------------------|
| CES0000000001 | total_nonfarm |
| CES6500000001 | education_and_health |
| CES6000000001 | professional_and_business_services |
| CES3100000001 | manufacturing |

**Citation (adapt for your narrative):**  
U.S. Bureau of Labor Statistics, Current Employment Statistics [program], series [IDs], retrieved from BLS Public Data API."""

def latest_json_path() -> Path:
    paths = sorted(RAW_BLS.glob("ces_sample_*.json"))
    if not paths:
        print("No ces_sample_*.json in data/raw/bls/. Run fetch_bls_series.py first.", file=sys.stderr)
        sys.exit(1)
    return paths[-1]


def parse_bls(payload: dict) -> pd.DataFrame:
    rows = []
    for block in payload.get("Results", {}).get("series", []):
        sid = block.get("seriesID", "")
        label = SERIES_LABELS.get(sid, sid)
        for pt in block.get("data", []):
            year = int(pt["year"])
            period = pt["period"]  # M01..M13
            if not period.startswith("M"):
                continue
            month = int(period[1:])
            value = float(pt["value"])
            rows.append(
                {
                    "series_id": sid,
                    "series_label": label,
                    "year": year,
                    "month": month,
                    "observation_date": f"{year:04d}-{month:02d}-01",
                    "employment_thousands_sa": value,
                }
            )
    return pd.DataFrame(rows)


def main() -> None:
    raw_path = latest_json_path()
    payload = json.loads(raw_path.read_text(encoding="utf-8"))
    if payload.get("status") != "REQUEST_SUCCEEDED":
        print("BLS JSON status not succeeded:", payload.get("status"), file=sys.stderr)
        sys.exit(2)

    df = parse_bls(payload)
    PROCESSED.mkdir(parents=True, exist_ok=True)
    META.mkdir(parents=True, exist_ok=True)

    out_csv = PROCESSED / "bls_ces_national_monthly_long.csv"
    df.sort_values(["series_label", "year", "month"]).to_csv(out_csv, index=False)

    snap_lines = [
        "# Data snapshot — preparation for DSAN 5200 narrative",
        "",
        "This file is generated by `scripts/materialize_bls_latest.py`.",
        "",
        "## Source",
        "",
        SOURCE_LINES.format(retrieval_date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")),
        "",
        "## Basic statistics (employment, thousands, SA)",
        "",
    ]

    for label, g in df.groupby("series_label"):
        gs = g.sort_values(["year", "month"])
        v = gs["employment_thousands_sa"]
        last = gs.iloc[-1]
        snap_lines.append(f"### `{label}`")
        snap_lines.append("")
        snap_lines.append(f"- **n (months):** {len(v)}")
        snap_lines.append(f"- **min:** {v.min():,.1f}")
        snap_lines.append(f"- **max:** {v.max():,.1f}")
        snap_lines.append(f"- **mean:** {v.mean():,.1f}")
        snap_lines.append(
            f"- **latest ({last['observation_date']}):** {last['employment_thousands_sa']:,.1f}"
        )
        snap_lines.append("")

    def posix(p: Path) -> str:
        return p.relative_to(ROOT).as_posix()

    snap_lines.extend(
        [
            "## Processed file",
            "",
            f"- `{posix(out_csv)}` — long format, one row per series × month.",
            "",
            "## Raw artifact",
            "",
            f"- `{posix(raw_path)}`",
            "",
        ]
    )

    snap_path = META / "DATA_SNAPSHOT.md"
    snap_path.write_text("\n".join(snap_lines), encoding="utf-8")

    print(f"Wrote {out_csv}")
    print(f"Wrote {snap_path}")
    print(f"From raw: {raw_path}")


if __name__ == "__main__":
    main()
